### ISSUE TITLE
Missing logs from uncaught errors when filling forms

### ISSUE THREAD

**Issue by derickl** [medic/cht-conf-test-harness#137]
**Describe the bug**
Some form errors crash enketo and are not logged

**To Reproduce**
Assuming you have a question `name` and a calculate `household_name` that concatenates `name` with ` Household`, the expression would fail to evaluate if name had a `"` character as part of its input.

The following failure is in cht-core.

>Could not evaluate: concat(../../contact/name, ' Household'), message: Failed to execute 'evaluate' on 'Document': The string 'concat("He A"", " Household")' is not a valid XPath expression.

The following is a stack trace from harness from an uncaught error
>Error: Evaluation failed: FormLogicError
      at ExecutionContext._evaluateInternal (node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
      at process._tickCallback (internal/process/next_tick.js:68:7)

**What did you expect?**
A clear description of the error

**Screenshots**

**Environment:**
Desktop: Latest Chrome & Firefox

**Comment by KicaRonaldOkello** [comment]
The exact example given in this issue has been fixed in the later versions of harness. The expression evaluates. @derickl
