### ISSUE TITLE
semver is a production dependency

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-conf-test-harness#208]
Some configurations with npm (mix of local linked packages) yields the following:

```
Error: Cannot find module 'semver'
Require stack:
- /home/kenn/config-itech/cares/node_modules/cht-conf-test-harness/src/cht-core-factory.js
- /home/kenn/config-itech/cares/node_modules/cht-conf-test-harness/src/harness.js
- /home/kenn/config-itech/cares/test/app/adherence.test.js
- /home/kenn/config-itech/cares/node_modules/mocha/lib/mocha.js
- /home/kenn/config-itech/cares/node_modules/mocha/index.js
- /home/kenn/config-itech/cares/node_modules/mocha/bin/_mocha
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/kenn/config-itech/cares/node_modules/cht-conf-test-harness/src/cht-core-factory.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/kenn/config-itech/cares/node_modules/cht-conf-test-harness/src/harness.js:12:24)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/kenn/config-itech/cares/test/app/adherence.test.js:2:25)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at /home/kenn/config-itech/cares/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/kenn/config-itech/cares/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/home/kenn/config-itech/cares/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/home/kenn/config-itech/cares/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/kenn/config-itech/cares/node_modules/cht-conf-test-harness/src/cht-core-factory.js',
    '/home/kenn/config-itech/cares/node_modules/cht-conf-test-harness/src/harness.js',
    '/home/kenn/config-itech/cares/test/app/adherence.test.js',
    '/home/kenn/config-itech/cares/node_modules/mocha/lib/mocha.js',
    '/home/kenn/config-itech/cares/node_modules/mocha/index.js',
    '/home/kenn/config-itech/cares/node_modules/mocha/bin/_mocha'
  ]
}
```

**Environment:**
 - Version: 2.4.2

**Comment by kennsippell** [comment]
package.json has [semver in dev modules](https://github.com/medic/cht-conf-test-harness/blob/master/package.json#L38)
semver is used in production (non-packaged) code [here](https://github.com/medic/cht-conf-test-harness/blob/master/src/cht-core-factory.js#L1)
