### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'data') in HTMLSelectElement

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-conf-test-harness#210]
```
     Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'data')
    at HTMLSelectElement.eval (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/select2/dist/js/select2.js?:5682:25)
    at Function.each (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/jquery/dist/jquery.js?:381:19)
    at jQuery.fn.init.each (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/jquery/dist/jquery.js?:203:17)
    at jQuery.fn.init.$.fn.select2 (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/select2/dist/js/select2.js?:5672:14)
    at HTMLSelectElement.eval (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/src/js/enketo/widgets/db-object-widget.js?:48:35)
    at HTMLSelectElement.dispatch (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/jquery/dist/jquery.js?:5429:27)
    at HTMLSelectElement.elemData.handle (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/jquery/dist/jquery.js?:5233:28)
    at Object.trigger (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/jquery/dist/jquery.js?:8715:12)
    at HTMLSelectElement.eval (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/jquery/dist/jquery.js?:8793:17)
    at Function.each (webpack://cht-conf-test-harness/./node_modules/cht-core-4-0/webapp/node_modules/jquery/dist/jquery.js?:381:19)
      at ExecutionContext._evaluateInternal (node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async ExecutionContext.evaluate (node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
      at async doFillPage (node_modules/cht-conf-test-harness/src/harness.js:760:22)
      at async Harness.fillForm (node_modules/cht-conf-test-harness/src/harness.js:316:24)
      at async Context.<anonymous> (test/tasks/cash_loan_reminder.spec.js:73:35)
```

**Comment by kennsippell** [comment]
Repro for this crash is in branch `210-select2-select`

**Comment by kennsippell** [comment]
https://github.com/medic/cht-conf-test-harness/pull/233 Attempts to add functionality for the db-object-widget. It isn't exactly blocked but it is taking a lot of time. For now I'd like to proceed with disabling the widget via https://github.com/medic/cht-conf-test-harness/pull/232

**Comment by kennsippell** [comment]
Apologies I forgot to publish. Can you run npm install cht-conf-test-harness@latest now? You should pick up 3.0.10

**Comment by Marina-Kenf** [comment]
Thanks so much!
